name       : timewarrior
version    : 1.1.1
release    : 1
source     :
    - https://taskwarrior.org/download/timew-1.1.1.tar.gz : 1f7d9a62e55fc5a3126433654ccb1fd7d2d135f06f05697f871897c9db77ccc9
license    : MIT
component  : office
summary    : Timewarrior tracks and reports time.
description: |
    Timewarrior is a command line time tracking application, which allows you to record time spent on activities. You may be tracking your time for curiosity, or because your work requires it. At its simplest, you tell it to start and stop tracking time.
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
