name       : timewarrior
version    : 1.3.0
release    : 4
source     :
    - https://github.com/GothenburgBitFactory/timewarrior/releases/download/v1.3.0/timew-1.3.0.tar.gz : c04c3ebefddd485323784409987ae66c11c3ce4c882a290c10934336a196f3e8
homepage   : https://timewarrior.net/
license    : MIT
component  : office
summary    : Timewarrior tracks and reports time.
description: |
    Timewarrior is a command line time tracking application, which allows you to record time spent on activities. You may be tracking your time for curiosity, or because your work requires it. At its simplest, you tell it to start and stop tracking time.
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/doc/timew/{AUTHORS,COPYING,ChangeLog,INSTALL,LICENSE,NEWS,README.md}
