name       : timewarrior
version    : 1.3.0
release    : 3
source     :
    - https://github.com/GothenburgBitFactory/timewarrior/releases/download/v1.3.0/timew-1.3.0.tar.gz : 1f3b9166a96637d3c098a7cfcff74ca61c41f13e2ca21f6c7ad6dd54cc74ac70
homepage   : https://timewarrior.net/
license    : MIT
component  : office
summary    : Timewarrior tracks and reports time.
description: |
    Timewarrior is a command line time tracking application, which allows you to record time spent on activities. You may be tracking your time for curiosity, or because your work requires it. At its simplest, you tell it to start and stop tracking time.
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/doc/timew/{AUTHORS,COPYING,ChangeLog,INSTALL,LICENSE,NEWS,README.md}
